version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: ./init.sh
    volumes:
      - .:/code
      - /code/node_modules
    ports:
      - 8000:8000
      - 3000:3000
    depends_on:
      - db
