from django.conf.urls import url
from chat.views import (ListPatientFiles,
                        ComposeView,
                        AutoCompleteEmail,
                        OutboxView,
                        SentMessageDetailView,
                        InboxPatientView,
                        ViewMessagePatient,
                        ArchiveMessageOutboxView,
                        ArchiveMessagePatientView,
                        ArchiveBoxPatientView,
                        ArchiveBoxHealthProfessionalView,
                        UnarchiveMessagePatientView,
                        UnarchiveMessageHealthProfessionalView,
                        CountMessagesView)

urlpatterns = (
    url(r'^list_patient_files/$', ListPatientFiles.as_view(), name='list_patient_files'),
    url(r'^inbox_patient/$', InboxPatientView.as_view(), name='inbox_patient'),
    url(r'^outbox/$', OutboxView.as_view(), name='outbox'),
    url(r'^compose/$', ComposeView.as_view(), name='compose'),
    url(r'^compose/ajax/autocomplete_email/$', AutoCompleteEmail.as_view(), name='autocomplete_email'),
    url(r'^view_message_patient/(?P<pk>[\w-]+)$', ViewMessagePatient.as_view(), name='view_message_patient'),
    url(r'^view_sent_message/(?P<pk>[\w-]+)$', SentMessageDetailView.as_view(), name='view_sent_message'),
    url(r'^archive_message_outbox/(?P<pk>[\w-]+)$', ArchiveMessageOutboxView.post, name='archive_message_outbox'),
    url(r'^archive_message_patient/(?P<pk>[\w-]+)$', ArchiveMessagePatientView.post, name='archive_message_patient'),
    url(r'^archive_box_health_professional/$',
        ArchiveBoxHealthProfessionalView.as_view(), name='archive_box_health_professional'),
    url(r'^archive_box_patient/$',
        ArchiveBoxPatientView.as_view(), name='archive_box_patient'),
    url(r'^unarchive_message_patient/(?P<pk>[\w-]+)$', UnarchiveMessagePatientView.post,
        name='unarchive_message_patient'),
    url(r'^unarchive_message_health_professional/(?P<pk>[\w-]+)$',
        UnarchiveMessageHealthProfessionalView.post, name='unarchive_message_health_professional'),
    url(r'^count_message/ajax/$', CountMessagesView.as_view(), name='count_messages'),
)
