# Local Django
from .sendmail import SendMail
from .addpatientview import AddPatientView
from .listlinkedpatientsview import ListLinkedPatientsView
from .confirmaccountview import ConfirmAccountView
from .confirmpasswordview import ConfirmPasswordView
from .deletehealthprofessional import DeleteHealthProfessional
from .loginview import LoginView
from .logoutview import LogoutView
from .registerhealthprofessionalview import RegisterHealthProfessionalView
from .registerpatientview import RegisterPatientView
from .resetpasswordview import ResetPasswordView
from .showhomepageview import ShowHomePageView
from .showpatientsview import ShowPatientsView
from .updatehealthprofessional import UpdateHealthProfessional
from .updatepatient import UpdatePatient
from .showhealthprofessionalview import ShowHealthProfessionalView
from .updatepasswordview import UpdateUserPassword
from .editprofile import EditProfileView