# Constants file.

# EXAMS CONSTANTS
ID_TUSS_MAX_LENGTH = 9
DESC_TUSS_MAX_LENGTH = 500

DESC_MAX_LENGTH = 500
DESC_MIN_LENGTH = 5


# CUSTOM EXAM MESSAGES VALIDATION MESSAGES.
DESC_SIZE = 'Description must be between 10 and 500 characters.'
